### ISSUE TITLE
[Imp] Use <nav> for navigation

### ISSUE THREAD

**Issue by Vlad-Iliescu** [sebastianpopa/sc_frontend#2]
E recomandat sa folosim `<nav>` pentru navigare.
Mai multe [aici](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav)

**Comment by sebastianpopa** [comment]
Solved
https://github.com/sebastianpopa/sc_frontend/commit/c739c59e1de81084f2ab69d274e110bd90ad4a01
