### ISSUE TITLE
[Bug] No placeholders for inputs

### ISSUE THREAD

**Issue by Vlad-Iliescu** [sebastianpopa/sc_frontend#4]
Una din cerinte era ca pe pagina de `contact` inputurile sa contina placeholders.
Mai multe detalii [aici](https://www.w3schools.com/tags/att_input_placeholder.asp).

**Comment by sebastianpopa** [comment]
Solved

https://github.com/sebastianpopa/sc_frontend/commit/bcaf09eef60b5e4fafbca46464dd96b2eda03d13
