### ISSUE TITLE
[Imp] Use label with inputs

### ISSUE THREAD

**Issue by Vlad-Iliescu** [sebastianpopa/sc_frontend#5]
https://github.com/sebastianpopa/sc_frontend/blob/bc41eaaa50262f5d0f15c32b9b5580200794f0ce/contact.html#L28

E de preferabil sa folosim `<label />` pentru inputuri. 
Mai multe detalii [aici](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label).

**Comment by sebastianpopa** [comment]
Solved

https://github.com/sebastianpopa/sc_frontend/commit/7e4b15bc041337999dfc29d1a09da6a01776ba99

**Comment by Vlad-Iliescu** [comment]
Incerca sa legi fiecare label cu inputul pe care il reprezinta. Important aici e sa folosesti atributul `for` din label impreuna cu `id`-ul inputului. Ideea finala e ca atunci cand dai click pe label sa iti faca focus la inputs sau toggle pt inputurile care accepta asta (radio/checkbox/...).

**Comment by sebastianpopa** [comment]
https://github.com/sebastianpopa/sc_frontend/commit/a561859100892fcd2194410f1db806b3f06c2c29
